### ISSUE TITLE
Make sure nio4r is working

### ISSUE THREAD

**Issue by ioquatix** [oracle/truffleruby#1527]
https://github.com/socketry/nio4r/issues/196

nio4r is used by ActionCable, Celluloid and Async.

It has both native and pure backends.

Both appear to have issues right now with truffleruby.

https://travis-ci.org/socketry/nio4r/builds/466712901

**Comment by eregon** [comment]
Currently the specs are stuck in
```
OpenSSL::SSL::SSLSocket
  behaves like an NIO selectable
```
From https://github.com/socketry/nio4r/issues/196#issuecomment-452660247
See https://travis-ci.org/socketry/nio4r/jobs/477285536

**Comment by ioquatix** [comment]
@eregon I recently fixed the specs so they are running on TruffleRuby, but there appear to be some issues still:

https://travis-ci.org/socketry/async/jobs/506071145

It's definitely better than before though.

**Comment by eregon** [comment]
Here is a run with the latest nightly:
```
Failures:

  1) TCPSocket behaves like an NIO selectable selects readable objects
     Failure/Error: expect(ready).to be_an Enumerable
       expected nil to be a kind of Enumerable
     Shared Example Group: "an NIO selectable" called from ./spec/nio/selectables/tcp_socket_spec.rb:72
     # ./spec/support/selectable_examples.rb:19:in `block (2 levels) in <top (required)>'

  2) TCPSocket behaves like an NIO bidirectional stream keeps readiness after the selectable has been closed
     Failure/Error: expect(monitor.readiness).to eq(:rw)

       expected: :rw
            got: :w

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -:rw
       +:w
     Shared Example Group: "an NIO bidirectional stream" called from ./spec/nio/selectables/tcp_socket_spec.rb:74
     # ./spec/support/selectable_examples.rb:80:in `block (3 levels) in <top (required)>'
     # /home/runner/.rubies/truffleruby-head/lib/truffle/truffle/cext.rb:1173:in `rb_yield'
     # ruby.c:1954:in `rb_yield'
     # ./ext/nio4r/selector.c:562:in `NIO_Selector_monitor_callback'
     # ./ext/libev/ev.c:3378:in `ev_invoke_pending'
     # ./ext/libev/ev.c:3850:in `ev_run'
     # ./ext/nio4r/selector.c:460:in `NIO_Selector_run'
     # ./ext/nio4r/selector.c:415:in `NIO_Selector_select_synchronized'
     # /home/runner/.rubies/truffleruby-head/lib/truffle/truffle/cext.rb:1605:in `rb_ensure'
     # ruby.c:2158:in `rb_ensure'
     # ./ext/nio4r/selector.c:286:in `NIO_Selector_synchronize'
     # ./ext/nio4r/selector.c:395:in `NIO_Selector_select'
     # /home/runner/.rubies/truffleruby-head/lib/truffle/truffle/cext_ruby.rb:39:in `select'
     # ./spec/support/selectable_examples.rb:79:in `block (2 levels) in <top (required)>'

  3) TCPSocket behaves like an NIO bidirectional stream selects readable and writable
     Failure/Error: expect(monitor.readiness).to eq(:rw)

       expected: :rw
            got: :w

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -:rw
       +:w
     Shared Example Group: "an NIO bidirectional stream" called from ./spec/nio/selectables/tcp_socket_spec.rb:74
     # ./spec/support/selectable_examples.rb:70:in `block (3 levels) in <top (required)>'
     # /home/runner/.rubies/truffleruby-head/lib/truffle/truffle/cext.rb:1173:in `rb_yield'
     # ruby.c:1954:in `rb_yield'
     # ./ext/nio4r/selector.c:562:in `NIO_Selector_monitor_callback'
     # ./ext/libev/ev.c:3378:in `ev_invoke_pending'
     # ./ext/libev/ev.c:3850:in `ev_run'
     # ./ext/nio4r/selector.c:460:in `NIO_Selector_run'
     # ./ext/nio4r/selector.c:415:in `NIO_Selector_select_synchronized'
     # /home/runner/.rubies/truffleruby-head/lib/truffle/truffle/cext.rb:1605:in `rb_ensure'
     # ruby.c:2158:in `rb_ensure'
     # ./ext/nio4r/selector.c:286:in `NIO_Selector_synchronize'
     # ./ext/nio4r/selector.c:395:in `NIO_Selector_select'
     # /home/runner/.rubies/truffleruby-head/lib/truffle/truffle/cext_ruby.rb:39:in `select'
     # ./spec/support/selectable_examples.rb:69:in `block (2 levels) in <top (required)>'

  4) NIO::Selector timeouts waits for a timeout when selecting with reader
     Failure/Error: expect(Time.now - started_at).to be_within(select_precision).of(timeout)
       expected 2.559 to be within 0.2 of 2.0
     # ./spec/nio/selector_spec.rb:128:in `block (3 levels) in <top (required)>'

Finished in 15.34 seconds (files took 7.31 seconds to load)
```

4) sounds like the spec is too strict, e.g. there could be a GC right around the call.
The other 3 seem to be TurffleRuby bugs.

And with NIO4R_PURE=true:
```
Failures:

  1) TCPSocket behaves like an NIO bidirectional stream keeps readiness after the selectable has been closed
     Failure/Error: expect(monitor.readiness).to eq(:rw)

       expected: :rw
            got: :r

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -:rw
       +:r
     Shared Example Group: "an NIO bidirectional stream" called from ./spec/nio/selectables/tcp_socket_spec.rb:74
     # ./spec/support/selectable_examples.rb:80:in `block (3 levels) in <top (required)>'
     # ./lib/nio/selector.rb:115:in `block in select'
     # /home/runner/.rubies/truffleruby-head/lib/mri/set.rb:338:in `block in each_key'
     # /home/runner/.rubies/truffleruby-head/lib/mri/set.rb:338:in `each_pair'
     # /home/runner/.rubies/truffleruby-head/lib/mri/set.rb:338:in `each_key'
     # /home/runner/.rubies/truffleruby-head/lib/mri/set.rb:338:in `each'
     # ./lib/nio/selector.rb:115:in `select'
     # ./spec/support/selectable_examples.rb:79:in `block (2 levels) in <top (required)>'

  2) TCPSocket behaves like an NIO bidirectional stream selects readable and writable
     Failure/Error: expect(monitor.readiness).to eq(:rw)

       expected: :rw
            got: :r

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -:rw
       +:r
     Shared Example Group: "an NIO bidirectional stream" called from ./spec/nio/selectables/tcp_socket_spec.rb:74
     # ./spec/support/selectable_examples.rb:70:in `block (3 levels) in <top (required)>'
     # ./lib/nio/selector.rb:115:in `block in select'
     # /home/runner/.rubies/truffleruby-head/lib/mri/set.rb:338:in `block in each_key'
     # /home/runner/.rubies/truffleruby-head/lib/mri/set.rb:338:in `each_pair'
     # /home/runner/.rubies/truffleruby-head/lib/mri/set.rb:338:in `each_key'
     # /home/runner/.rubies/truffleruby-head/lib/mri/set.rb:338:in `each'
     # ./lib/nio/selector.rb:115:in `select'
     # ./spec/support/selectable_examples.rb:69:in `block (2 levels) in <top (required)>'

Finished in 14.03 seconds (files took 6.59 seconds to load)
111 examples, 2 failures, 1 pending
```

Probably TurffleRuby bugs.
