### ISSUE TITLE
listen gem test failures

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1579]
Around 90% of the specs pass on TruffleRuby 1.0.0-rc12:
```
329 examples, 32 failures, 1 pending
```
https://travis-ci.org/eregon/listen/jobs/490484766#L4839

The failures all fail at a high-level with incorrect `added`/`modified`/`removed` files.
We should investigate to find out the root cause.
Maybe @ioquatix can help?

**Comment by deepj** [comment]
@eregon only one spec is failing

```
Failures:

  1) Listen::Event::Processor#loop_for when stopped with pending changes does not sleep
     Failure/Error: expect(diff).to be < 0.01

       expected: < 0.01
            got:   0.011999845504760742
     # ./spec/lib/listen/event/processor_spec.rb:67:in `block (5 levels) in <top (required)>'

Finished in 4 minutes 7.3 seconds (files took 13.77 seconds to load)
321 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/lib/listen/event/processor_spec.rb:62 # Listen::Event::Processor#loop_for when stopped with pending changes does not sleep
```

**Comment by eregon** [comment]
I'll run with `truffleruby-head` in CI: https://travis-ci.org/github/eregon/listen/builds/682293871
Most of the failures could be due to too strict timeouts, but I didn't investigate so not sure.

**Comment by deepj** [comment]
There is a similar "issue" in `rom-sql`

```
Failures:

  1) ROM::Relation#lock with hitting the database with postgres locks rows for update
     Failure/Error: expect(elapsed_time).to be < timeout

       expected: < 0.2
            got:   0.8070001602172852
     # ./spec/unit/relation/lock_spec.rb:35:in `block (4 levels) in <top (required)>'

```

See https://github.com/rom-rb/rom-sql/blob/master/spec/unit/relation/lock_spec.rb#L35

For JRuby the timeout is 10x higher. I'll sent a PR to fix it in `rom-sql` for TruffleRuby too. But. Why the limits are for MRI lower than for JRuby?
