### ISSUE TITLE
Mail gem test failure:  Test Retriever find should work with frozen hash arguments

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2101]
Master Mail [gem](https://github.com/mikel/mail/) has just 1 test failure:
```
1) Test Retriever find should work with frozen hash arguments
     Failure/Error: expect(Mail.find({:count => 1}.freeze)).to eq @emails.first
     
       expected: #<Mail::Message:908056, Multipart: false, Headers: <From: you@you.com>, <To: mikel@me.com>, <Subject: testing>>
            got: #<Mail::Message:908056, Multipart: false, Headers: <From: you@you.com>, <To: mikel@me.com>, <Subject: testing>>
     
       (compared using ==)
     
       Diff:
         <The diff is empty, are your objects producing identical `#inspect` output?>
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-support-3.9.3/lib/rspec/support.rb:97:in `block in <module:Support>'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-support-3.9.3/lib/rspec/support.rb:106:in `call'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-support-3.9.3/lib/rspec/support.rb:106:in `notify_failure'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-expectations-3.9.2/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-expectations-3.9.2/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-expectations-3.9.2/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-expectations-3.9.2/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-expectations-3.9.2/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-expectations-3.9.2/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/mail/network/retriever_methods/test_retriever_spec.rb:41:in `block (3 levels) in <top (required)>'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:257:in `instance_exec'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:257:in `block in run'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:481:in `block in run'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:619:in `run_around_example_hooks_for'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:481:in `run'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:254:in `run'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:644:in `block in run_examples'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:640:in `map'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:640:in `run_examples'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:606:in `run'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:607:in `block in run'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:607:in `map'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:607:in `run'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `map'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/configuration.rb:2058:in `with_suite_hooks'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:115:in `run_specs'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:89:in `run'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:71:in `run'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/exe/rspec:4:in `<main>'
```

```
truffleruby 20.3.0-dev-ff4b7dfd, like ruby 2.6.6, GraalVM CE Native [x86_64-darwin]
```
