### ISSUE TITLE
Support the Nokogiri gem

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#62]
We need to support Nokogiri, particular as it's used so much in testing gems. As with `openssl` (#61) we are using [Sulong](https://github.com/graalvm/sulong) as described in our RubyConf talk [Ruby's C Extension Problem and How We're Fixing It](https://www.youtube.com/watch?v=YLtjkP9bD_U).

[Current status](https://github.com/oracle/truffleruby/issues/62#issuecomment-362065726):
**We now support Nokogiri**, but it always uses a shared installation of libxml2, and so you need the libxml2 headers (and libraries) on the system (e.g., `apt-get install libxml2-dev libxslt-dev` on Debian-based).

On GitHub Actions, that means you need:
```yaml
    - run: sudo apt-get -yqq install libxml2-dev libxslt-dev
      if: startsWith(matrix.ruby, 'truffleruby')
# before
    - uses: ruby/setup-ruby@v1
```

If you use `ruby/setup-ruby` with `bundler-cache: true`, then that is automatically done by setup-ruby:
```yaml
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: truffleruby
        bundler-cache: true # automatically installs libxml2-dev libxslt-dev if nokogiri is in the lockfile
```

At some point we hope to be able to support building the in-tree libxml2 library like is done on MRI.
